// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig} from "prisma/config";
import dotenv from "dotenv";

// Determine which env file to load based on NODE_ENV (defaults to dev)
const env = process.env.NODE_ENV || "dev";
const envFiles: Record<string, string> = {
  dev: ".env.development",
  prod: ".env.production",
  test: ".env.testing",
};

const envFile = envFiles[env] || ".env.development";

// Load the env file relative to the project root
dotenv.config({
  path: `./src/env/${envFile}`,
});


export default defineConfig({
  schema: "prisma/schema",
  datasource: {
    url: process.env.DB_URL,
  },
});